/** Все тексты интерфейса — в одном месте. */
export const S = {
  app: {
    title: 'СОА · Лабораторная №2',
    variant: 'вариант 73126',
    services: 'Сервисы',
    check: 'проверить',
    spaceMarine: 'SpaceMarine',
    starship: 'Starship',
  },
  nav: {
    marines: 'Десантники',
    marinesCaption: 'коллекция, фильтры, сортировка',
    extras: 'Сводные операции',
    extrasCaption: 'подсчёт и поиск',
    ships: 'Корабли',
    shipsCaption: 'экипажи и высадка',
  },
  common: {
    add: '+ Добавить',
    apply: 'Применить',
    reset: 'Сбросить',
    cancel: 'Отмена',
    close: 'Закрыть',
    delete: 'Удалить',
    save: 'Сохранить',
    create: 'Создать',
    edit: 'Изменить',
    loading: 'Загрузка…',
    nothingFound: 'Ничего не найдено',
    yes: 'да',
    no: 'нет',
    any: 'любая',
    anyone: 'не важно',
    empty: '—',
    filters: 'Фильтры',
    sorting: 'Сортировка',
    sortDefault: 'по возрастанию id',
    total: 'Всего',
    page: 'страница',
    of: 'из',
    perPage: (n: number) => `по ${n}`,
    noChanges: 'Изменений нет',
  },
  errors: {
    byCode: {
      0: 'Нет связи с сервисом',
      400: 'Некорректный запрос',
      404: 'Не найдено',
      409: 'Конфликт',
      422: 'Данные нарушают ограничения',
      503: 'Сервис недоступен',
    } as Record<number, string>,
    other: 'Ошибка',
    violations: 'Нарушенные ограничения',
    notJson: 'Ответ не в формате JSON',
    unexpected: (status: number) => `Неожиданный ответ: ${status}`,
  },
  marine: {
    title: 'Десантники',
    subtitle: 'Коллекция объектов SpaceMarine',
    fields: {
      id: 'ID',
      name: 'Имя',
      category: 'Категория',
      health: 'Здоровье',
      loyal: 'Верен Империуму',
      x: 'Координата X',
      y: 'Координата Y',
      coordinates: 'Координаты',
      chapter: 'Орден',
      legion: 'Легион',
      achievements: 'Достижения',
      created: 'Создан',
    },
    newTitle: 'Новый десантник',
    viewTitle: (id: number) => `Десантник №${id}`,
    editTitle: (id: number) => `Десантник №${id} — изменение`,
    deleteTitle: 'Удалить десантника?',
    deleteText: (id: number, name: string) => `Десантник №${id} «${name}» будет удалён.`,
    created: (id: number) => `Десантник №${id} создан`,
    updated: (id: number) => `Десантник №${id} обновлён`,
    deleted: (id: number) => `Десантник №${id} удалён`,
  },
  extras: {
    title: 'Сводные операции',
    subtitle: 'Дополнительные операции первого сервиса',
    byChapter: 'Десантники ордена',
    legionHint: 'пусто — любой легион',
    count: 'Посчитать',
    healthAbove: 'Здоровье больше заданного',
    threshold: 'Порог',
    namePrefix: 'Поиск по началу имени',
    prefix: 'Начало имени',
    find: 'Найти',
    marinesCount: 'Десантников',
    found: (n: number) => `Найдено: ${n}`,
  },
  ship: {
    title: 'Корабли',
    subtitle: 'Десантные корабли и их экипажи',
    fields: { id: 'ID', name: 'Название', crew: 'Экипаж' },
    newTitle: 'Новый корабль',
    viewTitle: (id: number) => `Корабль №${id}`,
    deleteTitle: 'Удалить корабль?',
    deleteText: (id: number, name: string) => `Корабль №${id} «${name}» будет удалён.`,
    crew: 'Экипаж',
    noCrew: 'Экипажа нет',
    board: 'Посадить',
    unload: 'Высадить',
    marineToBoard: 'Десантник',
    created: (id: number) => `Корабль №${id} создан`,
    renamed: 'Название сохранено',
    deleted: (id: number) => `Корабль №${id} удалён`,
    boarded: (marine: number, ship: number) => `Десантник №${marine} на борту корабля №${ship}`,
    crewSize: (n: number) => (n === 0 ? '—' : String(n)),
  },
} as const;
