-- Идентификатор корабля теперь может выдавать база: базовое создание без id в URL.
-- BY DEFAULT сохраняет возможность явного id для эндпоинта /create/{id}/{name}.
-- Запуск: psql -h localhost -U <логин> -d studs -f db/migrate-001-starship-identity.sql
ALTER TABLE starship ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
-- Последовательность стартует после уже существующих номеров
SELECT setval(pg_get_serial_sequence('starship', 'id'), COALESCE((SELECT max(id) FROM starship), 0) + 1, false);
