-- Схема ЛР2. Раскатывается вручную; Hibernate работает в режиме validate и только
-- сверяет соответствие, ничего не создавая. Так DDL остаётся воспроизводимым
-- и лежит в репозитории, а не порождается на лету.
--
-- Запуск:
--   psql -h localhost -U <логин> -d studs -f db/schema.sql
--
-- Объекты создаются в схеме по умолчанию (search_path), то есть в личной схеме студента.

-- ---------------------------------------------------------------------------
-- Сервис 1: коллекция десантников
-- ---------------------------------------------------------------------------
CREATE TABLE space_marine (
    id                    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  varchar(255)                NOT NULL,
    coordinates_x         integer                     NOT NULL,
    coordinates_y         double precision            NOT NULL,
    -- Точность до миллисекунд — не косметика: Postgres по умолчанию хранит микросекунды,
    -- и фильтр по точному равенству creationDate не совпал бы никогда, так как клиент
    -- присылает миллисекунды в формате ISO-8601.
    creation_date         timestamp(3) with time zone NOT NULL,
    health                real                        NOT NULL,
    loyal                 boolean                     NOT NULL,
    achievements          varchar(1000),
    category              varchar(16)                 NOT NULL,
    chapter_name          varchar(255),
    chapter_parent_legion varchar(255),

    -- Ограничения дублируют инварианты домена: приложение — не единственный путь к данным.
    CONSTRAINT ck_marine_id       CHECK (id > 0),
    CONSTRAINT ck_marine_name     CHECK (length(btrim(name)) > 0),
    CONSTRAINT ck_marine_health   CHECK (health > 0),
    CONSTRAINT ck_marine_coord_y  CHECK (coordinates_y <= 12),
    CONSTRAINT ck_marine_category CHECK (category IN ('SCOUT', 'SUPPRESSOR', 'TACTICAL', 'HELIX')),
    CONSTRAINT ck_marine_chapter_name CHECK (chapter_name IS NULL OR length(btrim(chapter_name)) > 0),
    -- Запрещаем «легион без ордена»: иначе Hibernate прочитал бы полупустой встроенный объект.
    CONSTRAINT ck_marine_chapter_consistent CHECK (chapter_name IS NOT NULL OR chapter_parent_legion IS NULL)
);

-- Под операцию поиска минимального health и под самые вероятные фильтры и сортировки.
CREATE INDEX ix_marine_health       ON space_marine (health);
CREATE INDEX ix_marine_name         ON space_marine (name);
CREATE INDEX ix_marine_category     ON space_marine (category);
CREATE INDEX ix_marine_chapter_name ON space_marine (chapter_name);

-- ---------------------------------------------------------------------------
-- Сервис 2: десантные корабли
-- ---------------------------------------------------------------------------
CREATE TABLE starship (
    -- BY DEFAULT, а не ALWAYS: эндпоинт спецификации ЛР1 передаёт id в URL,
    -- базовое создание берёт следующий номер из последовательности этой же колонки.
    id   bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,

    CONSTRAINT ck_ship_id   CHECK (id > 0),
    CONSTRAINT ck_ship_name CHECK (length(btrim(name)) > 0)
);

CREATE TABLE starship_marine (
    starship_id     bigint  NOT NULL REFERENCES starship (id) ON DELETE CASCADE,
    -- Внешнего ключа на space_marine намеренно нет: это ссылка в другой сервис,
    -- связь поддерживается только через REST. Граница сервисов важнее ссылочной целостности.
    space_marine_id integer NOT NULL,
    boarded_at      timestamp(3) with time zone NOT NULL DEFAULT now(),

    PRIMARY KEY (starship_id, space_marine_id),
    -- Десантник может быть только на одном корабле; сервис проверяет это до записи,
    -- а индекс закрывает гонку двух одновременных посадок.
    CONSTRAINT uq_ship_marine_single UNIQUE (space_marine_id),
    CONSTRAINT ck_ship_marine_ref CHECK (space_marine_id > 0)
);
