package ru.ifmo.soa.spacemarine.adapter.persistence

import jakarta.persistence.Column
import jakarta.persistence.Embeddable
import jakarta.persistence.Embedded
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Table
import ru.ifmo.soa.spacemarine.domain.model.AstartesCategory
import java.time.Instant

/**
 * Персистентная модель десантника.
 *
 * Намеренно отделена от доменной [ru.ifmo.soa.spacemarine.domain.model.SpaceMarine]:
 * домен не должен повторять форму таблицы и зависеть от JPA. Цена — один маппер,
 * выигрыш — свобода менять схему БД, не трогая бизнес-правила.
 */
@Entity
@Table(name = "space_marine")
class SpaceMarineEntity(

    /** `IDENTITY` поверх `GENERATED BY DEFAULT AS IDENTITY`: последовательность стартует с 1, значит `id > 0`. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    var id: Int? = null,

    @Column(name = "name", nullable = false)
    var name: String = "",

    @Embedded
    var coordinates: CoordinatesEmbeddable = CoordinatesEmbeddable(),

    /** Дата создания неизменяема: спецификация помечает поле `readOnly`. */
    @Column(name = "creation_date", nullable = false, updatable = false)
    var creationDate: Instant = Instant.EPOCH,

    @Column(name = "health", nullable = false)
    var health: Float = 0f,

    @Column(name = "loyal", nullable = false)
    var loyal: Boolean = false,

    @Column(name = "achievements")
    var achievements: String? = null,

    /**
     * Хранится строкой, а не порядковым номером: иначе таблица нечитаема,
     * а добавление значения в середину перечисления тихо переразметит существующие строки.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false, length = 16)
    var category: AstartesCategory = AstartesCategory.SCOUT,

    @Embedded
    var chapter: ChapterEmbeddable? = null,
)

@Embeddable
class CoordinatesEmbeddable(
    @Column(name = "coordinates_x", nullable = false)
    var x: Int = 0,

    @Column(name = "coordinates_y", nullable = false)
    var y: Double = 0.0,
)

@Embeddable
class ChapterEmbeddable(
    @Column(name = "chapter_name")
    var name: String? = null,

    @Column(name = "chapter_parent_legion")
    var parentLegion: String? = null,
)
